version: "3"
services:
  vuesns_web:
    build: .
    volumes:
      - ./web:/var/www/html/vuesns
    ports:
      - 8081:8081
      - 3000:3000
  vuesns_database:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5434:5432
